export const AGGREGATE_REPORTS = [
  { id: 'i', name: 'Reporting Institutions' },
  { id: '1', name: 'Appliations by Tract' },
  { id: '2', name: 'Loans Purchased by Tract' },
  { id: '3-1', name: 'Loans Sold by Tract' },
  { id: '3-2', name: 'Loans Sold by Purchaser Type' },
  { id: '4-1', name: 'FHA, FSA/RHS and VA Purchases by Race' },
  { id: '4-2', name: 'Conventional Purchases by Race' },
  { id: '4-3', name: 'Refinancings by Race' },
  { id: '4-4', name: 'Home Improvements by Race' },
  { id: '4-5', name: 'Multi-Family Loans by Race' },
  { id: '4-6', name: 'Nonoccupant Loans by Race' },
  { id: '4-7', name: 'Manufactured Homes by Race' },
  { id: '5-1', name: 'FHA, FSA/RHS and VA by App Income' },
  { id: '5-2', name: 'Conv Purchases by App Income' },
  { id: '5-3', name: 'Refinancings by App Income' },
  { id: '5-4', name: 'Home Improvements by App Income' },
  { id: '5-6', name: 'Nonoccupant Loans by Income' },
  { id: '5-7', name: 'Manufactured Homes by Income' },
  { id: '7-1', name: 'FHA, FSA/RHS and VA by Tract Income' },
  { id: '7-2', name: 'Conv Purchases by Tract Income' },
  { id: '7-3', name: 'Refinancings by Tract Income' },
  { id: '7-4', name: 'Home Improvements by Tract Income' },
  { id: '7-5', name: 'Multi-Family Loans by Tract Income' },
  { id: '7-6', name: 'Nonoccupant Loans by Tract Income' },
  { id: '7-7', name: 'Manufactured Homes by Tract Income' },
  { id: '8-1', name: 'FHA, FSA/RHS and VA Purchase Denials' },
  { id: '8-2', name: 'Conv Home-Purchase Denials' },
  { id: '8-3', name: 'Refinancing Denials' },
  { id: '8-4', name: 'Home Improvement Denials' },
  { id: '8-5', name: 'Multi-Family Denials' },
  { id: '8-6', name: 'Nonoccupant Loan Denials' },
  { id: '8-7', name: 'Manufactured Home Denials' },
  { id: '9', name: 'Loan by Med Age of Homes' },
  { id: '11-1', name: 'FHA Home-Pur Pricing Info First' },
  { id: '11-2', name: 'VA Home-Pur Pricing Info First' },
  { id: '11-3', name: 'Conv Home-Pur Pricing Info First' },
  { id: '11-4', name: 'Conv Home-Pur Pricing Info Junior' },
  { id: '11-5', name: 'FHA Refi Pricing Info First' },
  { id: '11-6', name: 'VA Refi Pricing Info First' },
  { id: '11-7', name: 'Conv Refi Pricing Info First' },
  { id: '11-8', name: 'Conv Refi Pricing Info Junior' },
  { id: '11-9', name: 'Conv Home-Imp Pricing Info First' },
  { id: '11-10', name: 'Conv Home-Imp Pricing Info Junior' },
  { id: '12-1', name: 'Conv Manuf Home-Pur First' },
  { id: '12-2', name: 'Conv Manuf Home-Pur Pricing Info First' },
  { id: 'A1', name: 'Loan Sale by Loan Type 1 to 4 Families' },
  { id: 'A2', name: 'Loan Sale by Loan Type Manufactured' },
  { id: 'A3', name: 'Loan Sale by Loan Type Multi-Family' },
  { id: 'A4', name: 'Preapproval Conv Home-Pur First' },
  { id: 'B', name: 'Conv Price Info by Incidence and Level' }
]
